apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sklearn
  labels:
    app: inference
spec:
  selector:
    matchLabels:
      app: inference
  replicas: 1
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: dmitrylesh
        image: dmitrylesh/preds
        ports:
        - containerPort: 80
