apiVersion: v1
kind: Service
metadata:
  name: sklearn-inference
  namespace: default
  labels:
    app: sklearn-inference
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    nodePort: 31236
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sklearn-inference
  type: LoadBalancer