version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          
          docker build -t circleci-demo-docker:latest .
