version: 2.1
parameters:
  accountid:
    type: string
    default: "524768791364"
  region:
    type: string
    default: "us-west-1"
jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/proj5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make -i lint

  buildtrain:
    docker:
      - image: cimg/python:3.8.7
    requires: [lint]
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: | 
          make buildtrain

  train:
    docker:
      - image: cimg/python:3.8.7
    requires: [buildtrain]
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: "train and save model"
          command: |
            export key_id=$key_id
            echo $key_id
            export secret_key=$secret_key
            echo $secret_key
            docker pull dmitrylesh/train
            docker run -e secret_key -e key_id --rm -it dmitrylesh/train

  buildpushpres:
    docker:
      - image: cimg/python:3.8.7
    requires: [train]
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: | 
          make buildpreds            

workflows:
  lint:
    jobs:
      - lint
  buildtrain:
    jobs:
      - buildtrain
  train:
    jobs:
      - train
  buildpreds:
    jobs:
      - buildpreds
