apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference-service
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
spec:
  selector:
    matchLabels:
      app: inference-service
  replicas: 2
  template:
    metadata:
      labels:
        app: inference-service
    spec:
      containers:
      - name: dmitryleshpreds
        image: dmitrylesh/preds:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080